apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  # 结束后指定时间后删除
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: pi
          image: perl:5.34.0
          command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  # 重试次数
  backoffLimit: 4

